### PR TITLE
adding hash creation separately

### LINKED ISSUE #2: Crypto becomes the hell in browserify
When I browserify crypto, this imports a huge amount of unnecessary dependencies, how can we avoid this?

See: `/Users/mozilla/Proj/gits/simplerdf/node_modules/rdf-ext/node_modules/rdf-graph-array/node_modules/rdf-graph-abstract/node_modules/rdf-normalize/jsonld-normalize.js`

### PR DESCRIPTION
**Pull request by nicola**
Fixes #2
- I put a wrapper function around crypto to create a hash `./sha1.js`
- I put a wrapper function around `sha.js` (which imports only `sha.js/sha1`) to create a hash `./browser/sha1.js`
- standard!

It goes from 106k to 63K - however this is still a lot for such a library - do we really need sha?

### CODE REVIEW

**Comment by bergos** [comment]
The sha is part of the algorithm, so we need it. But jsonld.js contains a small [sha1 implementation for the browser](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js#L7617). I removed it in rdf-normalize, because I thought jsonld.js just uses it to avoid a browserify build step.

I had already gitter chat with @dlongley. He want's to restructure jsonld.js. The normalize part could become a separate module. So we would have to solve this only once. That would be the long term solution.

**Comment by bergos** [comment]
The commit contains also many changes in jsonld-normalize.js, beside the sha1 module import. That's all from the standard format, right? I should have added a comment. The code is based on [jsonld.js](https://github.com/digitalbazaar/jsonld.js/blob/master/js/jsonld.js). I tried to avoid any unneeded changes to simplify importing related patches from that project in the future.

**Comment by nicola** [comment]
ok I can revert standard - but leave the import properly - this change is needed - even if it is a temporary fix

**Comment by dlongley** [comment]
Once I've refactored the RDF Dataset Normalization stuff into its own module, we'll split things up further as needed (that includes SHA-1 and SHA-256, etc.)

**Comment by bergos** [comment]
fixed in #4

**Pull request closed without merging**
